name: 'NPM Custom Action'
description: 'Installing and Caching NPM Packages'
inputs:
  path-of-folder:  
    description: 'path to cache'
    required: true

runs:
  using: "composite"
  steps:
      - name: Install Dependencies
        run: npm install
        shell: bash

      - name: cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: ${{ inputs.path-of-folder }}
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}