on:
  pull_request: 
    types: 
     - opened

jobs:
    pr-action:
        runs-on: ubuntu-latest
        permissions: 
            issues: write
            pull-requests: write
        
        steps:
        - name: Post PR Comment
          uses: srikanth240695/docker-action-giphy-v1@main
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            giphy-api-key: ${{ secrets.GIPHY_API_KEY }} 

        - name: Post Java PR Comment
          uses: srikanth240695/js-action-pr@1.0.0-alpha
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
